volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  postgres:
    build:
        context: ./relational-data
        dockerfile: ./Dockerfile.dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_MULTIPLE_DATABASES=rooms
        - POSTGRES_USER=ikeya
        - POSTGRES_PASSWORD=test-databases
    ports:
        - 15432:5432
  fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app
  design_service:
    build:
        context: ./design_service
        dockerfile: ./Dockerfile.dev
    ports:
        - "8100:8100"
    volumes:
        - ./design_service:/app
    environment:
      DATABASE_URL: postgresql://admin:secret@postgres/rooms
      WAIT_HOSTS: postgres:5432

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ikeya@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_DISABLE_POSTFIX: 1

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
